version: "3.9"

services:
  payment_service:
    container_name: payment_service
    image: thayquedeptrai/payment_service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
