version: "3.9"

services:
  payment_service:
    container_name: payment_service
    image: thayquedeptrai/payment_service:latest
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

  product_service_db:
    container_name: product_service_db
    image: postgres:15.2-bullseye
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_DB=thayqueoi_db

  product_service:
    container_name: product_service
    image: thayquedeptrai/product_service:latest
    build:
      context: ./product_service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - DB_HOST=product_service_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=abcd1234
      - DB_NAME=thayqueoi_db

  shipment_service:
    container_name: shipment_service
    image: thayquedeptrai/shipment_service:latest
    build:
      context: ./shipment_service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"

  user_service_db:
    container_name: user_service_db
    image: postgres:15.2-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_DB=thayqueoi_db

  user_service:
    container_name: user_service
    image: thayquedeptrai/user_service:latest
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - DB_HOST=user_service_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=abcd1234
      - DB_NAME=thayqueoi_db
