version: "3.9"

services:
  product_service_db:
    container_name: product_service_db
    image: postgres:15.2-bullseye
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_DB=thayqueoi_db

  product_service:
    container_name: product_service
    image: thayquedeptrai/product_service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - DB_HOST=product_service_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=abcd1234
      - DB_NAME=thayqueoi_db
