# Generated by Django 4.1.7 on 2023-02-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='load_currency',
            new_name='local_currency',
        ),
    ]
