# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-03 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=5)),
                ('mode_of_payment', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
